//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajaIvana.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProbnaAgencijaEntities1 : DbContext
    {
        public ProbnaAgencijaEntities1()
            : base("name=ProbnaAgencijaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aranzmani> Aranzmanis { get; set; }
        public virtual DbSet<Destinacije> Destinacijes { get; set; }
        public virtual DbSet<Hoteli> Hotelis { get; set; }
        public virtual DbSet<Korisnici> Korisnicis { get; set; }
        public virtual DbSet<Rezervacije> Rezervacijes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Termini> Terminis { get; set; }
        public virtual DbSet<Usluge> Usluges { get; set; }
    }
}
