//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajaIvana.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aranzmani
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aranzmani()
        {
            this.Rezervacijes = new HashSet<Rezervacije>();
        }
    
        public int AranzmanID { get; set; }
        public int HotelID { get; set; }
        public int UslugaID { get; set; }
        public int TerminID { get; set; }
        public double Cena { get; set; }
        public int Raspolozivost { get; set; }
        public int Aktivan { get; set; }
    
        public virtual Hoteli Hoteli { get; set; }
        public virtual Termini Termini { get; set; }
        public virtual Usluge Usluge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacije> Rezervacijes { get; set; }
    }
}
