//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajaIvana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; //dodato

    public partial class Korisnici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnici()
        {
            this.Rezervacijes = new HashSet<Rezervacije>();
        }
    
        [Required(ErrorMessage="Obavezno je uneti sifru")]
        public int KorisnikID { get; set; }
        [Required(ErrorMessage = "Obavezno je uneti ime korisnika")]
        public string Ime { get; set; }

        [Required(ErrorMessage = "Obavezno je uneti prezime korisnika")]
        public string Prezime { get; set; }

        [Required(ErrorMessage = "Obavezno je uneti korisnicko ime")]
        public string KorisnickoIme { get; set; }

        [Required(ErrorMessage = "Obavezno je uneti lozinku")]
        public string Lozinka { get; set; }

        [Required(ErrorMessage = "Obavezno je uneti ulogu")]
        public int Uloga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacije> Rezervacijes { get; set; }
    }
}
